language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - valgrind
      - check
      - python3.4
before_install:
  - mkdir $HOME/bin && ln -s $(which python3.4) $HOME/bin/python3 && export PATH="$HOME/bin:$PATH"
script:
  - mvn clean test -q
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
jdk:
  - oraclejdk8
  - oraclejdk7
