cache:
  directories:
    - $HOME/.m2
language: java
before_install:
  - sudo apt-get update
  - sudo apt-get install -y valgrind check python3
script:
  - mvn clean test -q
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
