sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
script:
  - mvn clean test -q
  - mvn verify
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
